### PR TITLE
Show more progress info for the yt-dlp downloader

### PR DESCRIPTION
**Pull request by abdnh**
Firstly, thank you for the great app!

This PR shows more info about the download status like speed and ETA, as taken from yt-dlp's output.

I suck at design, so please feel free to close this and do a cleaner implementation if you like.
tmp7

### CODE REVIEW

**Comment by kylon** [comment]
hi, thanks for this PR!

this requires a few changes before the merge:

sharedown uses bootstrap 5, so a boostrap component must be used instead of custom html
since this is a yt-dlp only thing, i would not add a new button, something like a tooltip on top should work better 
code style: variables on top of the scope to improve readability

**Comment by abdnh** [comment]
What do you think about this?
image

**Comment by kylon** [comment]
my idea was something less invasive, for example [tooltips](https://getbootstrap.com/docs/5.1/components/tooltips/#examples) on hover on [.progress element](https://github.com/kylon/Sharedown/blob/ac261c5ff35acf5648dc4e74b54364fec98a6f78/sharedown/sharedown.html#L236) that is disabled by default (no data-bs-toggle) that it is enabled only for yt-dlp downloads and disabled when download is complete

**Comment by abdnh** [comment]
I ended up using a normal tooltip. It's a bit hard to find because of the other nearby URL tooltip, but it's fine for me.

tmp9

**Comment by kylon** [comment]
ok, it can be improved later, no problem

the nearby tooltip is there because you cannot use the .progress element for this, that was ok for bootstrap's tooltip only

a title attribute is already set [here](https://github.com/kylon/Sharedown/blob/ac261c5ff35acf5648dc4e74b54364fec98a6f78/sharedown/sharedown.js#L100), so you just save its value on start, set the new one on progress, and restore previous value on close.

progressElem = videoElem.querySelector('.progress').querySelector('span'); <- the element with the title attribute

**Pull request merged**
